// Curated header navigation — mirrors the live invitemart.in category menu
// (top categories + subcategories). Links use the same slugs as the live site.
export interface MenuChild {
  label: string;
  href: string;
}
export interface MenuItem {
  label: string; // full name (mega-menu heading + mobile)
  short: string; // condensed label for the desktop bar
  href: string;
  children: MenuChild[];
}

export const MENU: MenuItem[] = [
  {
    label: "Digital Wedding Invitations",
    short: "Wedding",
    href: "/product-category/digital-wedding-invitation",
    children: [
      { label: "Hindu Wedding", href: "/product-category/religion/hindu-wedding-invitation" },
      { label: "Punjabi Wedding", href: "/product-category/religion/punjabi-wedding-invitation" },
      { label: "Muslim Wedding", href: "/product-category/religion/muslim-wedding-invitation" },
      { label: "Rajasthani Wedding", href: "/product-category/religion/rajasthani-wedding-invitation" },
      { label: "Marwari Wedding", href: "/product-category/religion/marwari-wedding-invitation" },
      { label: "South Indian Wedding", href: "/product-category/religion/south-indian-wedding-invitation" },
      { label: "Marathi Wedding", href: "/product-category/religion/marathi-wedding-invitation" },
      { label: "Bengali Wedding", href: "/product-category/religion/bengali-wedding-invitation" },
      { label: "Christian Wedding", href: "/product-category/religion/christian-wedding-invitation" },
      { label: "Jain Wedding", href: "/product-category/religion/jain-wedding-invitation" },
      { label: "Traditional Wedding", href: "/product-category/style/traditional-wedding-invitation" },
      { label: "Lagna Patrika", href: "/product-category/lagna-patrika" },
      { label: "Floral Invitations", href: "/product-category/style/floral-invitation" },
      { label: "Photo Based", href: "/product-tag/photo-based-wedding-invitations" },
      { label: "Customised Story", href: "/product-category/style/customised-story-invitation" },
      { label: "Caricature Invitations", href: "/product-category/style/caricature-wedding-invitation" },
      { label: "Custom Invitations", href: "/product-category/style/custom-invitation" },
      { label: "Wedding Video", href: "/product-category/video-invitation/wedding-invitation-video" },
      { label: "Wedding PDF", href: "/product-category/pdf-invitation-card" },
      { label: "Bridal Shower", href: "/product-category/bridal-shower-invitation" },
      { label: "Haldi Ceremony", href: "/product-category/haldi-ceremony-invitation" },
      { label: "Mehndi Ceremony", href: "/product-category/mehndi-ceremony-invitation" },
      { label: "Ladies Sangeet", href: "/product-category/ladies-sangeet-invitations" },
      { label: "Wedding Reception", href: "/product-category/party-invitations/reception-party" },
      { label: "Wedding Thank You Card", href: "/product-category/wedding-thank-you-card" },
    ],
  },
  {
    label: "Engagement Invitations",
    short: "Engagement",
    href: "/product-category/engagement-invitation",
    children: [],
  },
  {
    label: "Baby & Kids",
    short: "Baby & Kids",
    href: "/product-category/baby-kids",
    children: [
      { label: "Baby Shower", href: "/product-category/baby-kids/baby-shower-invitation" },
      { label: "Birth Announcement", href: "/product-category/baby-kids/birth-announcement-invitation" },
      { label: "Naming Ceremony", href: "/product-category/baby-kids/naming-ceremony-invitation" },
      { label: "Mundan Ceremony", href: "/product-category/baby-kids/mundan-ceremony-invitations" },
      { label: "Dastar Bandi", href: "/product-category/baby-kids/dastar-bandi" },
      { label: "Thread Ceremony", href: "/product-category/baby-kids/thread-ceremony" },
      { label: "Birthday Party", href: "/product-category/baby-kids/birthday-party-invitation" },
      { label: "Kuan Poojan", href: "/product-category/baby-kids/kuan-poojan-invitation" },
      { label: "Aarangetram", href: "/product-category/baby-kids/aarangetram" },
      { label: "Annaprashan Ceremony", href: "/product-category/baby-kids/annaprashan-ceremony" },
      { label: "Baptism Ceremony", href: "/product-category/baby-kids/baptism-ceremony" },
      { label: "Cradle Ceremony", href: "/product-category/baby-kids/cradle-ceremony" },
      { label: "Dhoti Ceremony", href: "/product-category/baby-kids/dhoti-ceremony" },
      { label: "Ear Piercing", href: "/product-category/baby-kids/ear-piercing-ceremony" },
      { label: "Half Saree Ceremony", href: "/product-category/baby-kids/half-saree-ceremony" },
      { label: "Rice Ceremony", href: "/product-category/baby-kids/rice-ceremony-invitation" },
      { label: "Pregnancy Announcement", href: "/product-category/baby-kids/pregnancy-announcement" },
    ],
  },
  {
    label: "Party Invitations",
    short: "Party",
    href: "/product-category/party-invitations",
    children: [
      { label: "Anniversary Party", href: "/product-category/anniversary-party-invitation" },
      { label: "Cocktail Party", href: "/product-category/party-invitations/cocktail-party-invitation" },
      { label: "Dance Party", href: "/product-category/party-invitations/dance-party-invitations" },
      { label: "Pool Party", href: "/product-category/party-invitations/pool-party-invitation" },
      { label: "Reception Party", href: "/product-category/party-invitations/reception-party" },
      { label: "Grand Opening", href: "/product-category/grand-opening-invitation" },
      { label: "Housewarming", href: "/product-category/housewarming-invitation" },
      { label: "Holi Celebration", href: "/product-category/party-invitations/holi-celebration" },
      { label: "Lohri Celebration", href: "/product-category/party-invitations/lohri-celebration" },
      { label: "Barbeque Party", href: "/product-category/party-invitations/barbeque-party-invitation" },
      { label: "Dinner Party", href: "/product-category/party-invitations/dinner-party-invitation" },
      { label: "New Year Party", href: "/product-category/party-invitations/new-year-party-invitation" },
      { label: "Kitty Party", href: "/product-category/party-invitations/kitty-party-invitation" },
      { label: "Retirement Party", href: "/product-category/party-invitations/retirement-party" },
      { label: "Teej Invitations", href: "/product-category/party-invitations/teej-invitations" },
      { label: "Tea Invitation", href: "/product-category/party-invitations/tea-invitation" },
      { label: "Bachelor Party", href: "/product-category/party-invitations/bachelor-party-invitations" },
      { label: "Holy Communion", href: "/product-category/party-invitations/holy-communion" },
    ],
  },
  {
    label: "Puja Invitations",
    short: "Puja",
    href: "/product-category/pooja-invitations",
    children: [
      { label: "Balaji Chowki", href: "/product-category/pooja-invitations/balaji-chowki-invitation" },
      { label: "Ganesh Chaturthi", href: "/product-category/pooja-invitations/ganesh-chaturthi-invitation-card" },
      { label: "Mata Ki Chowki", href: "/product-category/pooja-invitations/mata-ki-chowki" },
      { label: "Sai Sandhya", href: "/product-category/pooja-invitations/sai-sandhya-invitation" },
      { label: "Sukhmani Sahib Path", href: "/product-category/pooja-invitations/shri-sukhmani-sahib-path-invitation" },
      { label: "Sunderkand Path", href: "/product-category/pooja-invitations/sunderkand-path-invitation" },
      { label: "Vastu Shanti", href: "/product-category/pooja-invitations/vastu-shanti-invitation" },
      { label: "Bhagwat Katha", href: "/product-category/pooja-invitations/bhagwat-katha" },
      { label: "Garba", href: "/product-category/party-invitations/garba-invitation" },
      { label: "Dandiya", href: "/product-category/pooja-invitations/dandiya-invitation" },
      { label: "Griha Pravesh", href: "/product-category/pooja-invitations/griha-pravesh" },
      { label: "Khatu Shyam", href: "/product-category/pooja-invitations/khatu-shyam-invitation" },
    ],
  },
  {
    label: "Festival Wishes",
    short: "Festivals",
    href: "/product-category/festival-wishes",
    children: [
      { label: "✦ Free Festival AI Maker", href: "/free-festival-invitations" },
      { label: "Diwali", href: "/product-category/festival-wishes/diwali-wishes" },
      { label: "Dhanteras", href: "/product-category/festival-wishes/dhanteras-wishes" },
      { label: "Holi", href: "/product-category/festival-wishes/holi" },
      { label: "Navratri", href: "/product-category/festival-wishes/navratri" },
      { label: "Dussehra", href: "/product-category/festival-wishes/dussehra" },
      { label: "Raksha Bandhan", href: "/product-category/festival-wishes/raksha-bandhan" },
      { label: "Krishna Janmashtami", href: "/product-category/festival-wishes/krishna-janmashtami" },
      { label: "Karwa Chauth", href: "/product-category/festival-wishes/karwa-chauth" },
      { label: "Maha Shivaratri", href: "/product-category/festival-wishes/maha-shivaratri" },
      { label: "Ganesha Chaturthi", href: "/product-category/festival-wishes/ganesha-chaturthi" },
      { label: "Guru Nanak Jayanti", href: "/product-category/festival-wishes/guru-nanak-jayanti" },
      { label: "Eid", href: "/product-category/festival-wishes/eid" },
      { label: "Merry Christmas", href: "/product-category/festival-wishes/merry-christmas-wishes" },
      { label: "New Year", href: "/product-category/festival-wishes/new-year" },
      { label: "Lohri", href: "/product-category/festival-wishes/lohri" },
      { label: "Pongal", href: "/product-category/festival-wishes/pongal" },
      { label: "Vasant Panchami", href: "/product-category/festival-wishes/vasant-panchami" },
      { label: "Rama Navami", href: "/product-category/festival-wishes/rama-navami" },
      { label: "Republic Day", href: "/product-category/festival-wishes/republic-day-of-india" },
      { label: "Independence Day", href: "/product-category/festival-wishes/independence-day-of-india" },
      { label: "Mother's Day", href: "/product-category/festival-wishes/mothers-day" },
      { label: "Father's Day", href: "/product-category/festival-wishes/fathers-day" },
      { label: "Valentine's Day", href: "/product-category/festival-wishes/valentines-day" },
      { label: "Friendship Day", href: "/product-category/festival-wishes/friendship-day" },
    ],
  },
];
