// Google Merchant Center product feed (RSS 2.0 + g: namespace).
// Merchant Center fetches this URL on a schedule and creates/updates listings.
//   https://invitemart.in/feeds/google-merchant.xml
//
// Data comes from data/feed.json, generated by scripts/build-catalog.mjs from
// the self-hosted catalog (no WordPress needed).
import { readFileSync } from "node:fs";
import path from "node:path";

// Merchant Center re-fetches daily; regenerate at most every 6h.
export const revalidate = 21600;

const SITE = "https://invitemart.in";
const BRAND = "InviteMart";
// Arts & Entertainment > Party & Celebration > Gift Giving > Greeting & Note Cards
const GOOGLE_CATEGORY = "96";

interface FeedItem {
  id: string;
  title: string;
  desc: string;
  slug: string;
  image: string;
  extra: string[];
  regular: string;
  sale: string | null;
  minor: number;
  type: string;
}

/** XML-escape plain text (used for attribute-ish values, not CDATA blocks). */
function esc(s: string): string {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/** CDATA-wrap, defusing any accidental "]]>" terminator. */
function cdata(s: string): string {
  return `<![CDATA[${String(s).replace(/]]>/g, "]]&gt;")}]]>`;
}

/** minor units ("59900", 2) -> "599.00 INR" */
function price(minorValue: string, minorUnit: number): string {
  const n = Number(minorValue);
  if (!Number.isFinite(n)) return "";
  return `${(n / Math.pow(10, minorUnit)).toFixed(2)} INR`;
}

function item(p: FeedItem): string {
  const regular = price(p.regular, p.minor);
  const sale = p.sale ? price(p.sale, p.minor) : "";
  const parts = [
    `<g:id>${esc(p.id)}</g:id>`,
    `<title>${cdata(p.title)}</title>`,
    `<description>${cdata(p.desc)}</description>`,
    `<link>${esc(`${SITE}/product/${p.slug}`)}</link>`,
    `<g:image_link>${esc(p.image)}</g:image_link>`,
    ...p.extra.map((u) => `<g:additional_image_link>${esc(u)}</g:additional_image_link>`),
    `<g:availability>in_stock</g:availability>`,
    `<g:condition>new</g:condition>`,
    regular ? `<g:price>${regular}</g:price>` : "",
    sale && sale !== regular ? `<g:sale_price>${sale}</g:sale_price>` : "",
    `<g:brand>${esc(BRAND)}</g:brand>`,
    // custom-made digital designs have no manufacturer GTIN/MPN
    `<g:identifier_exists>no</g:identifier_exists>`,
    `<g:google_product_category>${GOOGLE_CATEGORY}</g:google_product_category>`,
    p.type ? `<g:product_type>${cdata(p.type)}</g:product_type>` : "",
    // delivered digitally — no shipping cost
    `<g:shipping><g:country>IN</g:country><g:service>Digital delivery</g:service><g:price>0.00 INR</g:price></g:shipping>`,
  ].filter(Boolean);
  return `<item>${parts.join("")}</item>`;
}

export async function GET() {
  let feed: FeedItem[] = [];
  try {
    feed = JSON.parse(
      readFileSync(path.join(process.cwd(), "data", "feed.json"), "utf8")
    ) as FeedItem[];
  } catch {
    feed = [];
  }

  const xml =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<rss version="2.0" xmlns:g="http://base.google.com/ns/1.0">\n<channel>\n` +
    `<title>${cdata("InviteMart — Digital Invitation Cards & Videos")}</title>\n` +
    `<link>${SITE}</link>\n` +
    `<description>${cdata(
      "Personalised digital invitation cards, eCards, PDFs and invitation videos for weddings, birthdays, festivals and every celebration."
    )}</description>\n` +
    feed.map(item).join("\n") +
    `\n</channel>\n</rss>\n`;

  return new Response(xml, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      "Cache-Control": "public, max-age=0, s-maxage=21600, stale-while-revalidate=86400",
      "X-Feed-Items": String(feed.length),
    },
  });
}
